[package]
name = "generate_gif"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]
path = "src/lib.rs"

[dependencies]
gif = "0.14.0"
image = "0.25.9"
rayon = "1.11.0"
